"""initial schema

Revision ID: ab666d6606d8
Revises: 
Create Date: 2026-08-30 19:48:52.610320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab666d6606d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('statement_hash', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('statement_latex', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=512), nullable=False),
    sa.Column('answer_type', sa.String(length=16), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_questions_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_statement_hash'), ['statement_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('guest_token', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('peak_elo', sa.Integer(), nullable=True),
    sa.Column('placement_done', sa.Boolean(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('floor_shields_used', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_guest_token'), ['guest_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.Column('question_ids_json', sa.Text(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('wrong_a', sa.Integer(), nullable=False),
    sa.Column('wrong_b', sa.Integer(), nullable=False),
    sa.Column('time_ms_a', sa.Integer(), nullable=False),
    sa.Column('time_ms_b', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('is_draw', sa.Boolean(), nullable=False),
    sa.Column('elo_before_a', sa.Integer(), nullable=True),
    sa.Column('elo_before_b', sa.Integer(), nullable=True),
    sa.Column('elo_delta_a', sa.Integer(), nullable=True),
    sa.Column('elo_delta_b', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage_progress', sa.Integer(), nullable=False),
    sa.Column('manim_code', sa.Text(), nullable=True),
    sa.Column('narration_json', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=512), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fallback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_jobs_prompt_hash'), ['prompt_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('whiteboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('canvas_json', sa.Text(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whiteboards_user_id'), ['user_id'], unique=False)

    op.create_table('match_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_given', sa.String(length=512), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_skip', sa.Boolean(), nullable=False),
    sa.Column('ms_elapsed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_answers_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_answers_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('video_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['video_job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('match_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_answers_match_id'))

    op.drop_table('match_answers')
    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whiteboards_user_id'))

    op.drop_table('whiteboards')
    with op.batch_alter_table('video_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_jobs_prompt_hash'))

    op.drop_table('video_jobs')
    op.drop_table('matches')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_guest_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic'))
        batch_op.drop_index(batch_op.f('ix_questions_statement_hash'))
        batch_op.drop_index(batch_op.f('ix_questions_level'))
        batch_op.drop_index(batch_op.f('ix_questions_external_id'))

    op.drop_table('questions')
    # ### end Alembic commands ###
